Controllers/TrainerController.cs
using FitnessTracker.Models;
using FitnessTracker.Repository;
using Microsoft.AspNetCore.Mvc;

namespace FitnessTracker.Controllers
{
    public class TrainerController : Controller
    {
        // GET: Trainer
        public ActionResult Index()
        {
            var trainers = TrainerRepository.GetAllTrainers();
            return View(trainers);
        }

        // GET: Trainer/Details/5
        public ActionResult Details(int id)
        {
            var trainer = TrainerRepository.GetTrainerById(id);
            if (trainer == null) return NotFound();
            return View(trainer);
        }

        // GET: Trainer/Create
        public ActionResult Create()
        {
            return View(new Trainer());
        }

        // POST: Trainer/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Trainer trainer)
        {
            if (ModelState.IsValid)
            {
                TrainerRepository.AddTrainer(trainer);
                return RedirectToAction("Index");
            }
            return View(trainer);
        }

        // GET: Trainer/Edit/5
        public ActionResult Edit(int id)
        {
            var trainer = TrainerRepository.GetTrainerById(id);
            if (trainer == null) return NotFound();
            return View(trainer);
        }

        // POST: Trainer/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Trainer trainer)
        {
            if (ModelState.IsValid)
            {
                TrainerRepository.UpdateTrainer(trainer);
                return RedirectToAction("Index");
            }
            return View(trainer);
        }

        // GET: Trainer/Delete/5
        public ActionResult Delete(int id)
        {
            var trainer = TrainerRepository.GetTrainerById(id);
            if (trainer == null) return NotFound();
            return View(trainer);
        }

        // POST: Trainer/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            TrainerRepository.DeleteTrainer(id);
            return RedirectToAction("Index");
        }
    }

}

Controllers/UserController.cs
using FitnessTracker.Models;
using FitnessTracker.Repository;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace FitnessTracker.Controllers
{
    public class UserController : Controller
    {
        // GET: User
        public ActionResult Index()
        {
            var users = UserRepository.GetAllUsers();
            return View(users);
        }

        // GET: User/Details/5
        public ActionResult Details(int id)
        {
            var user = UserRepository.GetUserById(id);
            if (user == null) return NotFound();
            return View(user);
        }

        // GET: User/Create
        public ActionResult Create()
        {
            ViewBag.Trainers = new SelectList(TrainerRepository.GetAllTrainers(), "TrainerId", "Name");
            return View(new User());
        }

        // POST: User/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(User user)
        {
            if (ModelState.IsValid)
            {
                UserRepository.AddUser(user);
                return RedirectToAction("Index");
            }
            return View(user);
        }

        // GET: User/Edit/5
        public ActionResult Edit(int id)
        {
            var user = UserRepository.GetUserById(id);
            if (user == null) return NotFound();
            return View(user);
        }

        // POST: User/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(User user)
        {
            if (ModelState.IsValid)
            {
                UserRepository.UpdateUser(user);
                return RedirectToAction("Index");
            }
            return View(user);
        }

        // GET: User/Delete/5
        public ActionResult Delete(int id)
        {
            var user = UserRepository.GetUserById(id);
            if (user == null) return NotFound();
            return View(user);
        }

        // POST: User/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            UserRepository.DeleteUser(id);
            return RedirectToAction("Index");
        }
    }
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - FitnessTracker</title>
    <link href="~/css/bootstrap.min (5).css" rel="stylesheet" />
@*     <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
 *@    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/FitnessTracker.styles.css" asp-append-version="true" />

    @* <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet"> *@
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"></script>


</head>


<body>
    <header>

        <nav class="navbar navbar-expand-sm navbar-dark bg-dark border-bottom box-shadow">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Fitness Club</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarNav">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item pe-3 ps-5">
                            <a class="nav-link text-white" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-white pe-3 ps-5" asp-area="" asp-controller="User" asp-action="Index">Users</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-white pe-3 ps-5" asp-area="" asp-controller="Activities" asp-action="Index">Activity Log</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-white pe-3 ps-5" asp-area="" asp-controller="Trainer" asp-action="Index">Trainers</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-white ps-5" asp-area="" asp-controller="Home" asp-action="AboutUs">About Us</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>



        @* working code *@
@*         <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-dark border-bottom box-shadow">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Fitness Club</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item pe-3 ps-5">
                            <a class="nav-link text-white" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-white pe-3 ps-5" asp-area="" asp-controller="User" asp-action="Index">Users</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-white pe-3 ps-5" asp-area="" asp-controller="Activities" asp-action="Index">Activity Log</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-white ps-5" asp-area="" asp-controller="Home" asp-action="AboutUs">About Us</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav> *@

@*         <nav class="navbar navbar-expand-lg bg-primary" data-bs-theme="dark">
            <div class="container-fluid">
                <a class="navbar-brand" href="#">Navbar</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarColor01" aria-controls="navbarColor01" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarColor01">
                    <ul class="navbar-nav me-auto">
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="User" asp-action="Index">User</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="AboutUs">About Us</a>
                            </li>
                    </ul>
                </div>
            </div>
        </nav> *@
    </header>
    <div class="container-fluid home-background" style="padding-top:0px !important; padding-left:0 !important;">
        <main role="main" class="pb-0">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-white bg-dark">
        <div class="container">
            &copy; 2024 - Fitness Club - <a asp-area="" asp-controller="Home" asp-action="Index"></a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
   @*  <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script> *@
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

<style>
    .home-background {
        background-size: cover;
        background-position: center;
        min-height: 100vh;
        position: relative;
        z-index: 1;
        padding: 20px;
/*         background-image: url('images/gym.jpg'); */
        background-image: url('../gym.jpg');    
        color: white;
    }

        /* Adding a semi-transparent overlay */
        .home-background::before {
            content: "";
            position: absolute;
            top: 0;
            left: 0;
            width: 100%;
            height: 100%;
            background-color: rgba(0, 0, 0, 0.6); /* Dark overlay */
            z-index: -1;
        }
</style>